server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.application.name=EduManager
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/edumanager?useSSL=true&requireSSL=true&verifyServerCertificate=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Kevincho1994%
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false